version: "3.8"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --worker-class eventlet --reload --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./models:/models
      - ./services/web:/app
    expose:
      - 5000
  nginx:
    build: ./services/nginx
    ports:
      - 18000:80
    depends_on:
      - web
