version: "3.8"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --worker-class eventlet --reload --bind 0.0.0.0:5000 manage:app
    restart: always
    volumes:
      - ./models:/models/models
      - ./services/web:/app
    expose:
      - 5000
  nginx:
    build: ./services/nginx
    ports:
      - 18000:80
    volumes:
      - ./services/web/view:/www/static
    depends_on:
      - web
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=smartcapex
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=smartcapex
    volumes:
      - /data/db:/var/lib/postgresql
    ports:
      - 5432:5432
