version: "3.8"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --worker-class eventlet --reload --bind 0.0.0.0:5000 manage:app --timeout 600
    restart: always
    volumes:
      - ./models:/models/models
      - ./services/web:/app
    expose:
      - 5000
    depends_on:
      - redis
      - postgres
  nginx:
    build: ./services/nginx
    ports:
      - 18000:80
    volumes:
      - ./services/web/view:/www/static
    depends_on:
      - web
  redis:
    container_name: redis_host
    restart: always
    image: redis:latest
    ports:
      - 6379
    volumes:
      - /data/data:/data
  worker:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: celery -A project.tasks.celery worker -E
    restart: always
    volumes:
      - ./models:/models/models
      - ./services/web:/app
    depends_on:
      - redis
      - postgres
      - web
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=smartcapex
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=smartcapex
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /data/db:/var/lib/postgresql
    ports:
      - 5432:5432
